# Generated by Django 4.0.4 on 2022-05-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=6)),
                ('pic_url', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('class_name', models.CharField(max_length=64)),
            ],
        ),
    ]
