# Generated by Django 4.0.4 on 2022-05-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='age',
            field=models.IntegerField(default=22),
        ),
    ]
