# Generated by Django 4.0.4 on 2022-05-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_studentinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='class_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
