# Generated by Django 4.0.4 on 2022-06-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_studentinfo_class_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('class_name', models.CharField(max_length=32)),
                ('pic_url', models.CharField(blank=True, max_length=64, null=True)),
                ('audio_url', models.CharField(blank=True, max_length=64, null=True)),
                ('class_des', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
