# Generated by Django 4.0.4 on 2022-06-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_classinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinfo',
            name='class_number',
            field=models.IntegerField(unique=True),
        ),
    ]
