# Generated by Django 4.0.4 on 2022-06-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_classinfo_class_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='class_number',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='class_id',
            field=models.IntegerField(default=0),
        ),
    ]
