# Generated by Django 4.0.5 on 2022-06-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_classinfo_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classinfo',
            name='class_des2',
        ),
    ]
